### PR TITLE
Fix keyboard interruption on Windows

### PR DESCRIPTION
**Pull request by eviweb**
Works both on Windows and Linux.
Not tested on IOS but should work to.

### CODE REVIEW

**Comment by joh** [comment]
What is the issue this commit fixes?

**Comment by joh** [comment]
Oh, and printing ^C helps somehow?

**Comment by eviweb** [comment]
it seems...
Don't ask me why, please !

**Comment by joh** [comment]
That's so strange(!)
I wonder if it has anything to do with threads?
Also, won't printing ^C cause two ^Cs to be printed on Linux?

**Comment by eviweb** [comment]
Not on my Ubuntu desktop.

**Pull request merged**
